# Generated by Django 4.2.7 on 2023-11-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('uf', models.CharField(max_length=2)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
    ]
