# Generated by Django 4.2.4 on 2023-08-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id_fornecedores', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('cnpj', models.IntegerField()),
                ('email', models.TextField(max_length=255)),
                ('telefone', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('endereco', models.TextField(max_length=255)),
                ('numero', models.IntegerField()),
                ('uf', models.TextField(max_length=255)),
                ('cargo', models.TextField(max_length=255)),
            ],
        ),
    ]
