# Generated by Django 4.2.7 on 2023-11-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('UF', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Fornecedores',
        ),
    ]
