# Generated by Django 4.2.7 on 2023-11-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_fornecedores', '0002_fornecedor_delete_fornecedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='celular',
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
